# Generated by Django 3.1.3 on 2021-01-11 04:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchKey', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), size=None)),
                ('q1', models.PositiveSmallIntegerField()),
                ('q2', models.PositiveSmallIntegerField()),
                ('q3', models.PositiveSmallIntegerField()),
                ('q4', models.PositiveSmallIntegerField()),
                ('q5', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
