# Generated by Django 3.1.3 on 2021-01-18 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='timeStamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
