# Generated by Django 3.1.3 on 2021-01-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_study_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
