# Generated by Django 3.1.3 on 2021-01-18 17:38

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_study_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='date',
        ),
        migrations.AddField(
            model_name='study',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 17, 38, 38, 962308)),
        ),
        migrations.AlterField(
            model_name='study',
            name='q1',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='study',
            name='q2',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='study',
            name='q3',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='study',
            name='q4',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='study',
            name='q5',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='study',
            name='searchKey',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='timeStamps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=list, size=None),
        ),
    ]
