# Generated by Django 3.1.3 on 2021-01-18 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20210118_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 17, 41, 1, 585002, tzinfo=utc)),
        ),
    ]
