# Generated by Django 3.1.3 on 2021-01-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20210118_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
